#!/bin/sh

# write the ~/.ssh/config file, allowing copy of files to the static app
python mksshconfig.py

# collect static files
cd readthedocs && python manage.py collectstatic --noinput --settings=settings.dotcloud
